[package]
name = "darknet"
version = "0.1.0"
authors = ["alianse77"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darknet-sys = "0.1.0"
image = "0.23.1"
