[package]
name = "darknet"
version = "0.1.0"
authors = ["alianse77 <alianse77@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darknet-sys = {path = "../darknet-sys"}
image = "0.23.1"
